"""
Django settings for playawarded project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z7-q&3jf&%^u#z3km)j_mjnj&$@igw2!%yr2)5imiu1i!ka_83'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://likezao.com/', 'https://likezao.com', 'https://www.likezao.com']
AUTH_USER_MODEL = 'application.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'application.apps.ApplicationConfig',
    'django_crontab'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'playawarded.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'playawarded.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'playawarded',  
        'USER': 'root',  
        'PASSWORD': '6110',
        'HOST': '127.0.0.1',  
        'PORT': '3306',  
        'OPTIONS': {  
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
        }  
    }  
}  

AUTHENTICATION_BACKENDS = (
    'application.auth_backend.PasswordlessAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

#LANGUAGE_CODE = 'pt-BR'
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N=False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'
# STATIC_URL = '/app-assets/'


print(F"BASEDIR: {BASE_DIR}")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
#     # os.path.join('/Users/user/Desktop/playawarded/html-template/app-assets/vendors/css'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css/themes'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css/core/menu/menu-types'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css/core/colors'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css/pages'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/vendors/css'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/css/plugins/forms/validation'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/js/core'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/vendors/js/tables/datatable'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/js/scripts'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/js/scripts/datatables'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/js/scripts/forms'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/vendors/js'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/fonts/feather/fonts'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/data/locales'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/images/pages'),
#     os.path.join(str(BASE_DIR) + '/html-template/app-assets/'),
    
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATIC_ROOT = os.path.join(BASE_DIR, 'app-assets')

handler404 = 'mysite.views.my_custom_page_not_found_view'

CRONJOBS = [
    ('0 0 * * *', 'application.cron.execute')
]
