# Generated by Django 4.0.4 on 2022-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_rule_daily_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maximum_earning_per_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='maximum_per_click',
        ),
        migrations.RemoveField(
            model_name='user',
            name='minimum_per_click',
        ),
        migrations.RemoveField(
            model_name='user',
            name='minimum_withdrawl',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='additional_information',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
