# Generated by Django 4.0.4 on 2022-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_user_maximum_earning_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='today_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
