# Generated by Django 4.0.4 on 2022-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_bankdetail_total_earning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maximum_earning_per_day',
            field=models.FloatField(default=50),
        ),
    ]
